services:
  mc:
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19565:19565"
    environment:
      TYPE: forge
      EULA: "TRUE"
      MEMORY: "6G"
      VERSION: "1.12.2"
      FORGE_VERSION: "14.23.5.2860"
      JVM_XX_OPTS: >-
        -XX:+UseG1GC
        -XX:+UnlockExperimentalVMOptions
        -XX:+DisableExplicitGC
        -XX:G1NewSizePercent=30
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=8M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:SurvivorRatio=32
        -XX:+PerfDisableSharedMem
        -XX:MaxTenuringThreshold=1
      OPS: |
        Laserdrago
      TZ: PST
      ENABLE_RCON: "true"
      RCON_PASSWORD: "password"
      RCON_PORT: 25575
    volumes:
      - ../enigmatica:/data
    restart: on-failure
    mem_limit: 8G
    mem_reservation: 6G
    cpus: 6
    networks:
      minecraft:
        aliases:
          - minecraft
  prometheus:
    image: bitnami/prometheus
    tty: true
    stdin_open: true
    ports:
      - "127.0.0.1:9090:9090" 
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: on-failure
    networks:
      minecraft:
        aliases:
          - prometheus
  backup:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "6h"
      RCON_HOST: mc
      RCON_PORT: 25575
      RCON_PASSWORD: "password"
      BACKUP_METHOD: "restic"
      RESTIC_REPOSITORY: "s3:s3.amazonaws.com/zephyrus-enigmatica-server-backup"
      RESTIC_PASSWORD: "password"
      RESTIC_FORGET_ARGS: "--keep-daily 7 --keep-weekly 4 --keep-monthly 12"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: "us-west-1"
    volumes:
      - ../enigmatica:/data
    networks:
      minecraft:
        aliases:
          - backup
    restart: always


networks:
  minecraft:
    name: minecraft