- name: Load credentials from .env.yaml
  include_vars:
    file: ../../../.env.yml

- name: Create Grafana Service Account
  uri:
    url: "https://www.verturus.com/api/serviceaccounts"
    method: POST
    headers:
      Content-Type: "Application/json"
      Authorization: "Basic {{ (grafana_user ~ ':' ~ grafana_password) | b64encode }}"
    body_format: json
    body:
      name: "prometheus-service-account"
      role: "Admin"
    status_code: 200,201,409
  register: service_account_result

- name: Create Service Account Token
  uri: 
    url: "https://www.verturus.com/api/serviceaccounts/{{ service_account_result.json.id}}/tokens"
    method: POST
    headers:
      Content-Type: "Application/json"
      Authorization: "Basic {{ (grafana_user ~ ':' ~ grafana_password) | b64encode }}"
    body_format: json
    body: 
      name: "prometheus-token"
    status_code: 200, 201
  register: token_result
  when: service_account_result.status == 200 or service_account_result.status == 201

- name: Save Service Token to a file
  copy:
    content: "{{ token_result.json.key }}"
    dest: "../grafana-token.txt"
    mode: '0600'
  when: token_result.status is defined and (token_result.status == 200 or token_result.status == 201)
