services:
  mc:
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: forge
      EULA: "TRUE"
      MEMORY: "8G"
      VERSION: "1.12.2"
      FORGE_VERSION: "14.23.5.2860"
      JVM_XX_OPTS: >-
        -XX:+UseG1GC
        -XX:+UnlockExperimentalVMOptions
        -XX:+DisableExplicitGC
        -XX:G1NewSizePercent=30
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=8M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:SurvivorRatio=32
        -XX:+PerfDisableSharedMem
        -XX:MaxTenuringThreshold=1
    volumes:
      - ../enigmatica:/data
    restart: on-failure
    mem_limit: 10G
    mem_reservation: 8G
    cpus: 6
    OPS: |
      Laserdrago